[workspace]

[package]
name = "kuwahara"
version = "0.1.0"
edition = "2021"
description = "Kuwahara post-process effect."

[lib]
crate-type = ["cdylib"]

[dependencies]
renzora_plugin = { path = "../../sdk/plugin-api/renzora_plugin", default-features = false, features = ["libm"] }

[profile.dist]
inherits = "release"
opt-level = 2
strip = "symbols"
# no_std cannot unwind on stable.
panic = "abort"
